Repository PrestaShop/QANightlyResults, pull requests merged in 2024-07, with the labels that each got.

#240 Add autoupgared campaign to run in nightly
  src/Service/ReportPlaywrightImporter.php
  tests/Controller/ImportControllerTest.php
Labels: enhancement

#243 Import endpoints : replace _ by space
  src/Controller/ImportController.php
Labels: enhancement, Waiting for QA

#244 Merge `develop` into `master`
  composer.lock
  src/Controller/ImportController.php
Labels: QA :white_check_mark:

#247 Execution : Increased column size for version from 50 to 255
  src/Entity/Execution.php
Labels: bug, QA :white_check_mark:

#248 Merge `develop` into `master`
  src/Entity/Execution.php
Labels: enhancement, QA :white_check_mark:
