Repository PrestaShop/QANightlyResults, pull requests merged in 2025-01, with the labels that each got.

#330 Fix: increasing PHP memory
  Dockerfile
Labels: prestabulle1

#337 `/reports` : Add pagination (per default)
  src/Controller/ReportController.php
  src/Repository/ExecutionRepository.php
  tests/Controller/ReportControllerTest.php
Labels: enhancement

#345 Fixed Unit Tests
  tests/Controller/ReportControllerTest.php
Labels: bug
